Python 2.7:
  script:
  - export PY_EXE=python2.7
  - export EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  except:
  - tags
Python 3.4:
  script:
  - export PY_EXE=python3.4
  - export EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.4
  except:
  - tags
Python 2.6:
  script:
  - export PY_EXE=python3.4
  - export EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  except:
  - tags
